config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'books#index'
  resources :books, except: [:new]
=======
  get '/books' =>'lists#new'
  post 'lists' => 'lists#create'
  get 'lists/index'
  get 'lists/show'
  get 'lists/edit'
get '/' => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
>>>>>>> 8de91e6ac3c8246bd5cc4f6844c5d7e9449c476e
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
<<<<<<< HEAD
  validates :title, presence: true
  validates :body, presence: true
=======
>>>>>>> 8de91e6ac3c8246bd5cc4f6844c5d7e9449c476e
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      # DBへの保存成功
      flash[:success] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      # DBへの保存失敗
      @books = Book.all
      render "index"
    end
  end

  def show
    # @bookはbefore_action :set_bookで設定されています
  end

  def edit
    # @bookはbefore_action :set_bookで設定されています
  end

  def update
    if @book.update(book_params)
      # DBの更新成功
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      # DBの更新失敗
      render "edit"
    end
  end

  def destroy
  @book = Book.find(params[:id])
  @book.destroy
  flash[:success] = "Book was successfully destroyed."
  redirect_to books_pa
end


  private
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/index_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all.order(:id)
    @book = Book.new
    @book = Book.destroy
  end

  # 他のアクションも同様に設定
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
     @list = Book.new
  end

   def create
    list = List.new(list_params)
    list.save
    redirect_to '/top'
  end

  def index
  end

  def show
  end

  def edit
  end
   private
  # ストロングパラメータ
  def list_params
    params.require(:list).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<div>
  <%= flash.notice %>
</div>
<!-- app/views/books/edit.html.erb -->
<h1>Editing Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit 'Update Book' %>
  </div>
<% end %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>



<h2>New Book</h2>

<%= form_with(model: @book, local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/show.html.erb
<!-- app/views/books/show.html.erb -->


<p>
  <strong>Body:</strong>
  <%= @book.body %>
</p>
<p>
  <%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
<%= `link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' }` %>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>WebCampBackendNew</title>
  <meta name="csrf-param" content="authenticity_token">
  <meta name="csrf-token" content="9dlvxYgFeB+1HeAGnby5kzm/qZg58S5fFtMw9xRSfV6K95hoUjL2tQ2R4rt9dUA31lQq4ZSuPoA1Z6JOtoA6FA==">
  <link rel="stylesheet" media="all" href="/assets/application-d12397c･･･.css" data-turbolinks-track="reload">
  <script src="/assets/application-114264d･･･.is" data-turbolinks-track="reload">
  </script>
 </head>
 <body>
   <h1>
     ようこそ
     <strong>Bookers</strong>
     へ!
   </h1>
   <p>
     <strong>Bookers</strong>
     では、さまざまな書籍に関するあなたの意見や
   </p>
   <p>印象を共有し交換することができます</p>
   <p>
     <a href="/books">start</a>
   </p>
 </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<<<<<<< HEAD
<head>
  <title>Bookers</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

=======
  <head>
    <title>Bookers1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
>>>>>>> 8de91e6ac3c8246bd5cc4f6844c5d7e9449c476e

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Books</h1>
<!-- form_with部分 -->
<%= form_with model: Book.new do |f| %>
<h2>New book</h2>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
	
  <%= f.submit '投稿' %>
<% end %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>